alias = {
    "Aalborg": "AAL",
    "Aarhus": "AAR",
    "Aberdeen": "ABZ",
    "Agadir": "AGA",
    "Alghero": "AHO",
    "Alicante": "ALC",
    "Almeria": "LEI",
    "Amburgo": "HAM",
    "Amman Giordania": "AMM",
    "Amsterdam": "AMS",
    "Ancona": "AOI",
    "Asturie": "OVD",
    "Atene": "ATH",
    "Banja Luka": "BNX",
    "Barcellona (Girona)": "GRO",
    "Barcellona (Reus)": "REU",
    "Barcellona El Prat": "BCN",
    "Bari": "BRI",
    "Basilea": "BSL",
    "Belfast International": "BFS",
    "Beni Mellal": "BEM",
    "Bergerac": "EGC",
    "Berlino Brandeburgo": "BER",
    "Beziers": "BZR",
    "Biarritz": "BIQ",
    "Billund": "BLL",
    "Birmingham": "BHX",
    "Bodrum": "BJV",
    "Bologna": "BLQ",
    "Bordeaux": "BOD",
    "Bournemouth": "BOH",
    "Bratislava": "BTS",
    "Brema": "BRE",
    "Breslavia": "WRO",
    "Brindisi": "BDS",
    "Bristol": "BRS",
    "Brive": "BVE",
    "Brno": "BRQ",
    "Bruxelles (Charleroi)": "CRL",
    "Bruxelles Zaventem": "BRU",
    "Bucharest (Otopeni)": "OTP",
    "Budapest": "BUD",
    "Burgas": "BOJ",
    "Bydgoszcz": "BZG",
    "Cagliari": "CAG",
    "Carcassonne": "CCF",
    "Cardiff": "CWL",
    "Castellon (Valencia)": "CDT",
    "Catania": "CTA",
    "Cefalonia": "EFL",
    "Chania (Creta)": "CHQ",
    "Clermont Ferrand": "CFE",
    "Cluj": "CLJ",
    "Colonia": "CGN",
    "Copenaghen": "CPH",
    "Corfù": "CFU",
    "Cork": "ORK",
    "Cracovia": "KRK",
    "Crotone": "CRV",
    "Cuneo": "CUF",
    "Dalaman": "DLM",
    "Danzica": "GDN",
    "Derry": "LDY",
    "Dole": "DLE",
    "Dortmund": "DTM",
    "Dresden": "DRS",
    "Dublino": "DUB",
    "Dubrovnik": "DBV",
    "Düsseldorf (Weeze)": "NRN",
    "East Midlands": "EMA",
    "Edimburgo": "EDI",
    "Eindhoven": "EIN",
    "Errachidia": "ERH",
    "Essaouira": "ESU",
    "Exeter": "EXT",
    "Faro": "FAO",
    "Fez": "FEZ",
    "Figari": "FSC",
    "Fiume": "RJK",
    "Forlí": "FRL",
    "Francoforte (Hahn)": "HHN",
    "Fuerteventura": "FUE",
    "Genova": "GOA",
    "Glasgow": "GLA",
    "Glasgow (Prestwick)": "PIK",
    "Gran Canaria": "LPA",
    "Grenoble": "GNB",
    "Göteborg Landvetter": "GOT",
    "Helsinki": "HEL",
    "Heraklion Creta": "HER",
    "Iasi": "IAS",
    "Ibiza": "IBZ",
    "Jerez": "XRY",
    "Kalamata": "KLX",
    "Karlsruhe / Baden-Baden": "FKB",
    "Katowice": "KTW",
    "Kaunas": "KUN",
    "Kerry": "KIR",
    "Klagenfurt": "KLU",
    "Knock-Irlanda dell ovest": "NOC",
    "Kos": "KGS",
    "Kosice": "KSC",
    "La Rochelle": "LRH",
    "Lamezia": "SUF",
    "Lanzarote": "ACE",
    "Lappeenranta": "LPP",
    "Larnaca": "LCA",
    "Leeds Bradford": "LBA",
    "Lille": "LIL",
    "Limoges": "LIG",
    "Lipsia": "LEJ",
    "Lisbona": "LIS",
    "Liverpool": "LPL",
    "Lodz": "LCJ",
    "Londra (Gatwick)": "LGW",
    "Londra (Luton)": "LTN",
    "Londra (Stansted)": "STN",
    "Lourdes": "LDE",
    "Lublino": "LUZ",
    "Lussemburgo": "LUX",
    "Maastricht": "MST",
    "Madeira Funchal": "FNC",
    "Madrid": "MAD",
    "Malaga": "AGP",
    "Malmö": "MMX",
    "Malta": "MLA",
    "Manchester": "MAN",
    "Marrakech": "RAK",
    "Marsiglia": "MRS",
    "Memmingen": "FMM",
    "Milano Bergamo": "BGY",
    "Milano Malpensa": "MXP",
    "Minorca": "MAH",
    "Murcia International": "RMU",
    "Mykonos": "JMK",
    "Münster": "FMO",
    "Nador": "NDR",
    "Nantes": "NTE",
    "Napoli": "NAP",
    "Newcastle": "NCL",
    "Newquay Cornovaglia": "NQY",
    "Nimes": "FNI",
    "Nis": "INI",
    "Nizza": "NCE",
    "Norimberga": "NUE",
    "Norwich": "NWI",
    "Olbia": "OLB",
    "Olsztyn - Mazury": "SZY",
    "Osijek": "OSI",
    "Oslo": "OSL",
    "Oslo (Torp)": "TRF",
    "Ostrava": "OSR",
    "Ouarzazate": "OZZ",
    "Oujda": "OUD",
    "Paderborn": "PAD",
    "Pafos": "PFO",
    "Palanga": "PLQ",
    "Palermo": "PMO",
    "Palma": "PMI",
    "Pardubice": "PED",
    "Parigi (Beauvais)": "BVA",
    "Parigi (Vatry)": "XCR",
    "Parma": "PMF",
    "Perpignan": "PGF",
    "Perugia": "PEG",
    "Pescara": "PSR",
    "Pisa": "PSA",
    "Plovdiv": "PDV",
    "Podgorica": "TGD",
    "Poitiers": "PIS",
    "Pola": "PUY",
    "Ponta Delgada": "PDL",
    "Poprad - Tatry (Tatra Mountains)": "TAT",
    "Porto": "OPO",
    "Poznan": "POZ",
    "Praga": "PRG",
    "Preveza - Aktion": "PVK",
    "Rabat": "RBA",
    "Reggio Calabria": "REG",
    "Riga": "RIX",
    "Rimini": "RMI",
    "Rodez": "RDZ",
    "Rodi": "RHO",
    "Roma (Ciampino)": "CIA",
    "Roma (Fiumicino)": "FCO",
    "Rovaniemi - Lapponia": "RVN",
    "Rzeszow": "RZE",
    "Salisburgo": "SZG",
    "Salonicco": "SKG",
    "Santander": "SDR",
    "Santiago": "SCQ",
    "Santorini Nazionale": "JTR",
    "Saragozza": "ZAZ",
    "Sarajevo": "SJJ",
    "Shannon": "SNN",
    "Siviglia": "SVQ",
    "Skelleftea": "SFT",
    "Skiathos": "JSI",
    "Sofia": "SOF",
    "Spalato": "SPU",
    "Stettino": "SZZ",
    "Stoccolma Arlanda": "ARN",
    "Stoccolma Västerås": "VST",
    "Strasbourg": "SXB",
    "Tallinn": "TLL",
    "Tangeri": "TNG",
    "Teesside": "MME",
    "Tel Aviv": "TLV",
    "Tenerife (Nord)": "TFN",
    "Tenerife (Sud)": "TFS",
    "Terceira Lajes": "TER",
    "Tirana": "TIA",
    "Tolosa": "TLS",
    "Torino": "TRN",
    "Tours Valle della Loira": "TUF",
    "Trapani-Marsala": "TPS",
    "Trieste": "TRS",
    "Tétouan": "TTU",
    "Valencia": "VLC",
    "Valladolid": "VLL",
    "Varna": "VAR",
    "Varsavia (Chopin)": "WAW",
    "Varsavia (Modlin)": "WMI",
    "Venezia (Treviso)": "TSF",
    "Venezia M.Polo": "VCE",
    "Verona": "VRN",
    "Vienna": "VIE",
    "Vigo": "VGO",
    "Vilnius": "VNO",
    "Vitoria": "VIT",
    "Växjö Småland": "VXO",
    "Zacinto": "ZTH",
    "Zagabria": "ZAG",
    "Zara": "ZAD",
    "Örebro": "ORB"
}

inverted_alias = {value: key for key, value in alias.items()}