routes = {
    "Alghero": ["Barcellona El Prat", "Bari", "Billund", "Bologna", "Bordeaux", "Bratislava", "Bruxelles (Charleroi)",
                "Budapest", "Catania", "Cork", "Dublino", "Francoforte (Hahn)", "Katowice", "Londra (Stansted)",
                "Madrid", "Memmingen", "Milano Bergamo", "Milano Malpensa", "Napoli", "Palermo", "Pescara", "Pisa",
                "Venezia M.Polo"],
    "Ancona": ["Bruxelles (Charleroi)", "Catania", "Cracovia", "Düsseldorf (Weeze)", "Londra (Stansted)"],
    "Bari": ["Alghero", "Alicante", "Atene", "Barcellona (Girona)", "Berlino Brandeburgo", "Billund", "Bologna",
             "Bordeaux", "Bruxelles (Charleroi)", "Budapest", "Cagliari", "Catania", "Chania (Creta)", "Cracovia",
             "Dublino", "Dubrovnik", "Düsseldorf (Weeze)", "Edimburgo", "Francoforte (Hahn)", "Genova", "Ibiza",
             "Karlsruhe / Baden-Baden", "Katowice",
             "Kaunas", "Kos", "Londra (Stansted)", "Maastricht", "Madrid", "Malaga", "Malta", "Marsiglia",
             "Milano Bergamo",
             "Milano Malpensa", "Norimberga", "Palermo", "Parigi (Beauvais)", "Pisa", "Porto", "Poznan", "Praga",
             "Rodi", "Roma (Fiumicino)",
             "Santorini Nazionale", "Siviglia", "Skiathos", "Sofia", "Tel Aviv", "Tirana", "Tolosa", "Torino",
             "Trieste", "Valencia", "Varsavia (Modlin)",
             "Venezia M.Polo", "Verona", "Vienna", "Zacinto"],
    "Bologna": ["AlgheroAlicante", "Amman Giordania", "Atene", "Barcellona El Prat", "Bari", "Berlino Brandeburgo",
                "Billund", "Breslavia",
                "Brindisi", "Bruxelles (Charleroi)", "Bucharest (Otopeni)", "Budapest", "Cagliari", "Catania",
                "Chania (Creta)", "Colonia",
                "Copenaghen", "Corfù", "Cracovia", "Crotone", "Dublino", "Edimburgo", "Eindhoven", "Fez",
                "Fuerteventura", "Gran Canaria",
                "Heraklion Creta", "Ibiza", "Kos", "Lamezia", "Lanzarote", "Lisbona", "Londra (Luton)",
                "Londra (Stansted)", "Madrid", "Malaga",
                "Malta", "Manchester", "Marsiglia", "Minorca", "Mykonos", "Olbia", "Palermo", "Palma",
                "Parigi (Beauvais)", "Porto", "Praga", "Preveza - Aktion",
                "Reggio Calabria", "Rodi", "Salonicco", "Santander", "Santiago", "Saragozza", "Siviglia", "Sofia",
                "Stoccolma Arlanda", "Tel Aviv",
                "Tenerife (Sud)", "Tirana", "Tolosa", "Trapani-Marsala", "Valencia", "Varsavia (Modlin)", "Vienna",
                "Zara"],
    "Brindisi": ["Bologna", "Breslavia", "Bruxelles (Charleroi)", "Danzica", "Dublino", "Eindhoven", "Genova",
                 "Londra (Stansted)", "Madrid", "Manchester",
                 "Memmingen", "Milano Bergamo", "Milano Malpensa", "Palermo", "Parigi (Beauvais)", "Perugia", "Pisa",
                 "Roma (Fiumicino)", "Stoccolma Arlanda",
                 "Torino", "Trieste", "Venezia M.Polo", "Verona"],
    "Cagliari": ["Bari", "Bologna", "Bruxelles (Charleroi)", "Budapest", "Carcassonne", "Catania", "Cracovia", "Cuneo",
                 "Dublino", "Düsseldorf (Weeze)",
                 "Francoforte (Hahn)", "Genova", "Göteborg Landvetter", "Karlsruhe / Baden-Baden", "Londra (Stansted)",
                 "Madrid", "Malta", "Milano Bergamo",
                 "Milano Malpensa", "Napoli", "Norimberga", "Palermo", "Palma", "Parigi (Beauvais)", "Parma", "Perugia",
                 "Pisa", "Porto", "Poznan", "Rimini",
                 "Roma (Ciampino)", "Siviglia", "Torino", "Trieste", "Valencia", "Venezia M.Polo", "Verona", "Vienna"],
    "Catania": ["Alghero", "AnconaAtene", "Bari", "Berlino Brandeburgo", "Bologna", "Bruxelles (Charleroi)",
                "Bucharest (Otopeni)", "Budapest", "Cagliari",
                "Cracovia", "Eindhoven", "Francoforte (Hahn)", "Genova", "Heraklion Creta", "Katowice",
                "Londra (Luton)", "Londra (Stansted)", "Madrid",
                "Malta", "Marsiglia", "Milano Bergamo", "Milano Malpensa", "Napoli", "Parigi (Beauvais)", "Perugia",
                "Pescara", "Pisa", "Praga", "Rodi",
                "Roma (Fiumicino)", "Siviglia", "Sofia", "Tirana", "Torino", "Trieste", "Varsavia (Modlin)",
                "Venezia M.Polo", "Verona", "Vienna"],
    "Crotone": ["Bologna", "Milano Bergamo", "Torino", "Venezia (Treviso)"],
    "Cuneo": ["Cagliari", "Palermo"],
    "Forlì": ["Katowice", "Palermo"],
    "Genova": ["Bari", "Brindisi", "Bruxelles (Charleroi)", "Bucharest (Otopeni)", "Cagliari", "Catania", "Lamezia",
               "Londra (Stansted)", "Manchester", "Napoli", "Palermo"],
    "Lamezia": ["Bologna", "Bruxelles (Charleroi)", "Cracovia", "Francoforte (Hahn)", "Genova",
                "Karlsruhe / Baden-Baden", "Londra (Stansted)", "Malta", "Memmingen",
                "Milano Bergamo", "Milano Malpensa", "Norimberga", "Pisa", "Torino", "Valencia", "Venezia M.Polo",
                "Verona", "Vienna"],
    "Milano Bergamo": ['Agadir', 'Alghero', 'Alicante', 'Amburgo', 'Amman Giordania', 'AteneBarcellona El Prat', 'Bari',
                       'Belfast International', 'Beni Mellal',
                       'Berlino Brandeburgo', 'Biarritz', 'Billund', 'Birmingham', 'Bordeaux', 'Bratislava',
                       'Breslavia', 'Brindisi', 'Bristol', 'Brno',
                       'Bruxelles (Charleroi)', 'Bucharest (Otopeni)', 'Budapest', 'Cagliari', 'Castellon (Valencia)',
                       'Catania', 'Cefalonia', 'Chania (Creta)',
                       'Cluj', 'Colonia', 'Copenaghen', 'Corfù', 'Cork', 'Cracovia', 'Crotone', 'Danzica', 'Dublino',
                       'Dubrovnik', 'Düsseldorf (Weeze)',
                       'East Midlands', 'Edimburgo', 'Eindhoven', 'Faro', 'Fez', 'Francoforte (Hahn)', 'Fuerteventura',
                       'Gran Canaria', 'Göteborg Landvetter',
                       'Helsinki', 'Heraklion Creta', 'Iasi', 'Ibiza', 'Kalamata', 'Karlsruhe / Baden-Baden',
                       'Katowice', 'Kaunas', 'Knock-Irlanda dell ovest',
                       'Kos', 'Lamezia', 'Lanzarote', 'Lappeenranta', 'Lisbona', 'Liverpool', 'Lodz',
                       'Londra (Stansted)', 'Lourdes', 'Lublino', 'Lussemburgo',
                       'Madrid', 'Malaga', 'Malta', 'Manchester', 'Marrakech', 'Marsiglia', 'Minorca', 'Napoli',
                       'Newcastle', 'Olbia', 'Oslo (Torp)', 'Pafos',
                       'Palermo', 'Palma', 'Parigi (Beauvais)', 'Pescara', 'Porto', 'Poznan', 'Praga',
                       'Preveza - Aktion', 'Riga', 'Rodi', 'Rovaniemi - Lapponia',
                       'Salonicco', 'Santander', 'Santiago', 'Santorini Nazionale', 'Saragozza', 'Sarajevo', 'Siviglia',
                       'Skiathos', 'Sofia', 'Stoccolma Arlanda',
                       'Tallinn', 'Tangeri', 'Tel Aviv', 'Tenerife (Sud)', 'Tirana', 'Tolosa', 'Trapani-Marsala',
                       'Valencia', 'Varsavia (Modlin)', 'Vienna', 'Vilnius',
                       'Vitoria', 'Zacinto', 'Zagabria', 'Zara'],
    "Milano Malpensa": ["Alghero", "Alicante", "Atene", "Barcellona El Prat", "Bari", "Berlino Brandeburgo", "Brindisi",
                        "Bucharest (Otopeni)", "Budapest", "Cagliari",
                        "Catania", "Corfù", "Dublino", "Gran Canaria", "Heraklion Creta", "Kos", "Lamezia", "Lanzarote",
                        "Londra (Stansted)", "Madrid", "Malaga", "Malta",
                        "Manchester", "Marrakech", "Napoli", "Palermo", "Palma", "Parigi (Beauvais)", "Porto",
                        "Santorini Nazionale", "Siviglia", "Tallinn",
                        "Tenerife (Sud)", "Trapani-Marsala", "Valencia", "Vienna", "Zara"],
    "Napoli": ['Alghero', 'Barcellona El Prat', 'Bordeaux', 'Breslavia', 'Bruxelles (Charleroi)', 'Bucharest (Otopeni)',
               'Budapest', 'Cagliari', 'Catania',
               'Chania (Creta)', 'Copenaghen', 'Corfù', 'Cracovia', 'Danzica', 'Dublino', 'Edimburgo', 'Eindhoven',
               'Genova', 'Kaunas', 'Lisbona', 'Londra (Luton)',
               'Londra (Stansted)', 'Madrid', 'Malaga', 'Malta', 'Manchester', 'Marrakech', 'Marsiglia', 'Memmingen',
               'Milano Bergamo', 'Milano Malpensa', 'Minorca',
               'Mykonos', 'Norimberga', 'Pafos', 'Palermo', 'Palma', 'Parigi (Beauvais)', 'Praga', 'Rodi', 'Salonicco',
               'Santorini Nazionale', 'Shannon', 'Siviglia',
               'Sofia', 'Tel Aviv', 'Tenerife (Sud)', 'Tolosa', 'Torino', 'Trapani-Marsala', 'Trieste', 'Valencia',
               'Varsavia (Modlin)', 'Venezia M.Polo', 'Verona',
               'Vienna', 'Zacinto', 'Zagabria'],
    "Olbia": ['Bologna', 'Bruxelles (Charleroi)', 'Copenaghen', 'Cracovia', 'Dublino', 'Londra (Stansted)',
              'Milano Bergamo', 'Parigi (Beauvais)', 'Trieste', 'Vienna'],
    "Palermo": ['Alghero', 'Barcellona El Prat', 'Bari', 'Berlino Brandeburgo', 'Bologna', 'Breslavia', 'Brindisi',
                'Bruxelles (Charleroi)', 'Bucharest (Otopeni)',
                'Budapest', 'Cagliari', 'Colonia', 'Cracovia', 'Cuneo', 'Dublino', 'Edimburgo', 'Forlì',
                'Francoforte (Hahn)', 'Genova', 'Karlsruhe / Baden-Baden',
                'Londra (Stansted)', 'Madrid', 'Marsiglia', 'Memmingen', 'Milano Bergamo', 'Milano Malpensa', 'Napoli',
                'Norimberga', 'Parigi (Beauvais)', 'Parma',
                'Perugia', 'Pisa', 'Poznan', 'Rimini', 'Roma (Fiumicino)', 'Torino', 'Trieste', 'Valencia',
                'Venezia M.Polo', 'Verona', 'Vienna'],
    "Parma": ["Cagliari", "Malta", "Palermo"],
    "Perugia": ['Barcellona El Prat', 'Brindisi', 'Bruxelles (Charleroi)', 'Bucharest (Otopeni)', 'Cagliari', 'Catania',
                'Cracovia', 'Londra (Stansted)', 'Malta', 'Palermo'],
    "Pescara": ['Alghero', 'Barcellona (Girona)', 'Bruxelles (Charleroi)', 'Bucharest (Otopeni)', 'Catania', 'Cracovia',
                'Düsseldorf (Weeze)', 'Francoforte (Hahn)',
                'Londra (Stansted)', 'Malta', 'Memmingen', 'Milano Bergamo', 'Praga', 'Torino', 'Trapani-Marsala'],
    "Pisa": ['Alghero', 'Amman Giordania', 'Barcellona (Girona)', 'Bari', 'Berlino Brandeburgo', 'Billund',
             'Birmingham', 'Bordeaux', 'Breslavia', 'Brindisi',
             'Bruxelles (Charleroi)', 'Bruxelles Zaventem', 'Bucharest (Otopeni)', 'Budapest', 'Cagliari', 'Catania',
             'Cefalonia', 'Chania (Creta)', 'Copenaghen',
             'Corfù', 'Cork', 'Cracovia', 'Danzica', 'Dublino', 'East Midlands', 'Edimburgo', 'Eindhoven',
             'Fuerteventura', 'Glasgow (Prestwick)', 'Gran Canaria', 'Göteborg Landvetter', 'Ibiza', 'Kaunas', 'Kos',
             'Lamezia', 'Lisbona', 'Londra (Stansted)', 'Madrid', 'Malaga', 'Malta', 'Manchester', 'Marrakech',
             'Memmingen', 'Oslo (Torp)', 'Palermo', 'Palma', 'Parigi (Beauvais)', 'Porto', 'Praga', 'Rodi', 'Siviglia',
             'Skiathos', 'Stoccolma Arlanda', 'Tenerife (Sud)', 'Tirana', 'Trapani-Marsala', 'Valencia', 'Zagabria',
             'Zara'],
    "Reggio Calabria": ['Barcellona El Prat', 'Berlino Brandeburgo', 'Bologna', 'Manchester', 'Marsiglia', 'Tirana',
                        'Torino', 'Venezia M.Polo'],
    "Rimini": ['Budapest', 'Cagliari', 'Cracovia', 'Kaunas', 'Londra (Stansted)', 'Palermo', 'Praga', 'Vienna'],
    "Roma (Ciampino)": ['Amman Giordania', 'Bratislava', 'Breslavia', 'Bruxelles (Charleroi)', 'Bucharest (Otopeni)',
                        'Budapest',
                        'Cagliari', 'Corfù', 'Cracovia', 'Danzica', 'East Midlands', 'Edimburgo', 'Fez', 'Liverpool',
                        'Londra (Stansted)',
                        'Lourdes', 'Manchester', 'Marrakech', 'Pafos', 'Porto', 'Poznan', 'Rabat', 'Riga', 'Rodi',
                        'Salonicco', 'Siviglia',
                        'Sofia', 'Tallinn', 'Tangeri', 'Tirana', 'Varsavia (Modlin)'],
    "Roma (Fiumicino)": ['Alicante', 'Asturie', 'Atene', 'Barcellona El Prat', 'Bari', 'Berlino Brandeburgo', 'Billund',
                         'Bordeaux',
                         'Brindisi', 'Bruxelles Zaventem', 'Catania', 'Cefalonia', 'Chania (Creta)', 'Colonia',
                         'Copenaghen', 'Cork',
                         'Dublino', 'Dubrovnik', 'Eindhoven', 'Faro', 'Francoforte (Hahn)', 'Fuerteventura',
                         'Gran Canaria',
                         'Göteborg Landvetter', 'Ibiza', 'Katowice', 'Kos', 'Lisbona', 'Madrid', 'Malaga', 'Malta',
                         'Marsiglia',
                         'Memmingen', 'Minorca', 'Palermo', 'Palma', 'Parigi (Beauvais)', 'Poznan', 'Praga',
                         'Preveza - Aktion',
                         'Santander', 'Santorini Nazionale', 'Skiathos', 'Spalato', 'Stoccolma Arlanda', 'Tel Aviv',
                         'Tenerife (Sud)',
                         'Tolosa', 'Trapani-Marsala', 'Valencia', 'Vienna', 'Vilnius', 'Zacinto', 'Zagabria'],
    "Torino": ['Alicante', 'Barcellona El Prat', 'Bari', 'Belfast International', 'Birmingham', 'Brindisi', 'Bristol',
               'Bruxelles (Charleroi)', 'Cagliari', 'Catania', 'Copenaghen', 'Corfù', 'Cracovia', 'Crotone', 'Dublino',
               'Ibiza', 'Lamezia', 'Lanzarote', 'Londra (Luton)', 'Londra (Stansted)', 'Madrid', 'Malaga', 'Malta',
               'Manchester',
               'Marrakech', 'Napoli', 'Palermo', 'Parigi (Beauvais)', 'Pescara', 'Porto', 'Praga', 'Reggio Calabria',
               'Shannon',
               'Siviglia', 'Stoccolma Arlanda', 'Tel Aviv', 'Trapani-Marsala', 'Valencia', 'Vilnius'],
    "Trapani-Marsala": ['Billund', 'Bologna', 'Bordeaux', 'Bratislava', 'Bruxelles (Charleroi)', 'Düsseldorf (Weeze)',
                        'Karlsruhe / Baden-Baden', 'Katowice', 'Londra (Stansted)', 'Malta', 'Manchester',
                        'Milano Bergamo',
                        'Milano Malpensa', 'Napoli', 'Pescara', 'Pisa', 'Porto', 'Riga', 'Roma (Fiumicino)', 'Siviglia',
                        'Tolosa', 'Torino', 'Venezia (Treviso)'],
    "Trieste": ['Barcellona El Prat', 'Bari', 'Berlino Brandeburgo', 'Brindisi', 'Bruxelles (Charleroi)', 'Budapest',
                'Cagliari', 'Catania', 'Cracovia', 'Dublino', 'Londra (Stansted)', 'Malta', 'Napoli', 'Olbia',
                'Palermo',
                'Parigi (Beauvais)', 'Siviglia', 'Valencia'],
    "Venezia (Treviso)": ['Alicante', 'Amman Giordania', 'Berlino Brandeburgo', 'Billund', 'Breslavia',
                          'Bruxelles (Charleroi)',
                          'Bucharest (Otopeni)', 'Budapest', 'Chania (Creta)', 'Corfù', 'Cork', 'Cracovia', 'Crotone',
                          'Danzica',
                          'East Midlands', 'Eindhoven', 'Francoforte (Hahn)', 'Gran Canaria', 'Ibiza', 'Katowice',
                          'Kos',
                          'Londra (Luton)', 'Malaga', 'Malta', 'Marrakech', 'Marsiglia', 'Minorca', 'Pafos', 'Palma',
                          'Parigi (Beauvais)', 'Porto', 'Poznan', 'Praga', 'Riga', 'Salonicco', 'Santander',
                          'Saragozza',
                          'Siviglia', 'Sofia', 'Tallinn', 'Tel Aviv', 'Tenerife (Sud)', 'Tirana', 'Tolosa',
                          'Trapani-Marsala',
                          'Valencia', 'Varsavia (Modlin)', 'Vienna', 'Vilnius'],
    "Venezia M.Polo": ['Alicante', 'Amman Giordania', 'Alghero', 'Barcellona El Prat', 'Bari', 'Berlino Brandeburgo',
                       'Birmingham', 'Bordeaux', 'Bournemouth', 'Brindisi', 'Bristol', 'Cagliari', 'Catania', 'Colonia',
                       'Copenaghen', 'Cork', 'Dublino', 'Edimburgo', 'Helsinki', 'Lamezia', 'Lanzarote', 'Lisbona',
                       'Londra (Stansted)', 'Madrid', 'Manchester', 'Napoli', 'Palermo', 'Reggio Calabria',
                       'Stoccolma Arlanda', 'Vienna'],
    "Verona": ['Bari', 'Birmingham', 'Brindisi', 'Bruxelles (Charleroi)', 'Cagliari', 'Catania', 'Corfù', 'Dublino',
               'Lamezia',
               'Londra (Stansted)', 'Madrid', 'Manchester', 'Napoli', 'Palermo', 'Palma', 'Porto', 'Valencia']
}
